config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get 'login', to: 'devise/sessions#new', as: :login
  end
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :spaces, except: [:new, :create, :index] do
    resources :bookings, only: [:new, :create ]
  end

  resources :venues do
    resources :spaces, only: [:new, :create, :index] do
      resources :bookings, only: [:show ]
    end
  end

  resources :bookings, only: [:index, :destroy]
  get 'dashboard', to: 'dashboards#show', as: :dashboard


  namespace :api, defaults: { format: :json } do
    post 'webpush/subscribe', to: 'webpush#subscribe'
  end

end

app/models/space.rb
class Space < ApplicationRecord
  belongs_to :venue
  has_many :bookings
  has_one_attached :photo
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  before_action :set_space, only: %i[show edit update destroy]
  def index
    @venue = Venue.find(params[:venue_id])
    @spaces = Space.all
  end

  def show
    def all
      booking = Booking.order(date: :asc)
     end
  end

  def new
    @venue = Venue.find(params[:venue_id])
    @space = Space.new
    # authorize if owner -> yes. else no
  end

  def create
    @space = Space.new(space_params)
    @venue = Venue.find(params[:venue_id])
    @space.venue = @venue
    if @space.save
      redirect_to venue_path(@venue)
    else
      render :new
    end
  end

  def edit
    # authorize if owner -> yes. else no
  end

  def update
    if @space.update(space_params)
      redirect_to venue_path(@space.venue), notice: 'Space was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    # authorize if owner -> yes. else no
    @space.destroy
    redirect_to venue_path(@space.venue)
  end

  private

  def set_space
    @space = Space.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def space_params
    params.require(:space).permit(:name, :capacity, :photo, :description)
  end
  # Use callbacks to share
end

app/views/spaces/_form.html.erb
<%= simple_form_for [@venue, @space] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <%= f.input :name %>
    <%= f.input :capacity %>
    <%= f.input :description %>
    <%= f.input :photo, as: :file %>
    <%= f.button :submit, class:"d-flex justify-content-center text-white py-1 px-6 focus:outline-none hover:bg-blue-600 rounded-md text-lg bg-gradient-to-t from-blue-900 via-blue-600 to-blue-500" %>

<% end %>

app/views/spaces/_space.html.erb
<div class="p-4">
  <div class="h-full border-2 border-gray-200 border-opacity-60 rounded-xl shadow overflow-hidden">
    <div class="lg:h-48 md:h-36 w-full object-cover object-center bg-gray-200">
      <% if space.photo.attached? %>
        <%= cl_image_tag space.photo.key, height: 300, width: 400, crop: :fill, class: 'w-full h-full object-cover' %>
      <% end %>
    </div>
    <div class="p-6">
      <h1 class="title-font text-lg font-medium text-gray-900 mb-3"><%= space.name %></h1>
      <h2 class="tracking-widest text-xs title-font font-medium text-gray-400 mb-1"><%= @venue.name %></h2>
      <p class="leading-relaxed mb-3"><%= space.description %></p>
      <div class="flex justify-start justify-between">
        <div class="flex text-gray-600 items-right leading-none text-sm py-1">
          <i class="fas fa-laptop pr-2"></i>
          <p><%= space.capacity %> seats</p>
        </div>
<%# ADMIN %>
        <div class="d-flex">
          <div class="flex px-2">
            <% if current_user.venues.include?(@venue) %>
              <%= link_to  space_path(space), method: :delete, data: { confirm: "Are you sure you want to delete Venue?"}, class:"p-2" do %>
                <i class="fas fa-trash-alt " style=""></i>
                <%# <%= button_to ‘Delete space’, space_path(space), method: :delete, data: { confirm: "Are you sure you want to delete space?"} %>
              <% end %>
            <% end %>

            <% if current_user.venues.include?(@venue) %>
              <%= link_to  edit_space_path(space), class:"p-2" do %>
                <i class="fas fa-user-edit " style=""></i>
                <%# <%= button_to ‘Delete space’, space_path(space), method: :delete, data: { confirm: "Are you sure you want to delete space?"} %>
              <% end %>
            <% end %>
          </div>
          <div class="d-flex">
            <%= link_to 'Book now', new_space_booking_path(space), data: {turbolinks:"false"}, class:'flex-col text-white py-1 px-6 focus:outline-none hover:bg-blue-600 rounded-md text-lg bg-gradient-to-t from-blue-900 via-blue-600 to-blue-500' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/spaces/edit.html.erb
<section class="footer-ht bg-white p-8">
  <div class="d-flex justify-content-center">
    <div class="h-full mb-4 p-2 rounded-2xl">
      <h1 class="text-xl d-flex justify-content-center mt-4 mb-3 font-weight-bold"> Edit your space </h1>
      <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
        <div class="flex flex-col">
          <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
              <div class="p-3 max-w-xxl mx-auto">
                <%= render 'form', space: @space %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/spaces/index.html.erb
<section class="bg-white">
  <div class="container mx-auto">
  <%# VENUE NAME & ADDRESS %>
    <div     class="sm:px-8 sm:py-6 md:py-10">

      <div class="relative z-10 pb-3 sm:bg-none">
        <h2 class="text-xl font-semibold text-gray-900 sm:text-2xl sm:leading-7 sm:text-black md:text-3xl"><%= @venue.name %></h2>
        <div class="col-start-1 row-start-2">
          <div class="flex items-left text-sm font-medium sm:mt-2 sm:mb-2">
            <svg width="20" height="20" fill="currentColor" class="text-blue-700">
              <path d="M9.05 3.691c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.372 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.539 1.118l-2.8-2.034a1 1 0 00-1.176 0l-2.8 2.034c-.783.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.363-1.118l-2.8-2.034c-.784-.57-.381-1.81.587-1.81H7.03a1 1 0 00.95-.69L9.05 3.69z" />
            </svg>
            <div class="ml-1">
              <span class="text-gray-900">4.94</span>
              <span class="sm:hidden md:inline">(28)</span>
            </div>
            <div class="text-base font-normal mx-2">·</div>
            <p class="text-sm font-medium text-gray-700 sm:mb-1"><%= @venue.suburb %>, <%= @venue.state %>, <%= @venue.country %></p>
          </div>

        </div>
          <hr class="w-24 border-gray-400 hidden sm:block">
      </div>

      <%# AVAILABILITY %>
      <%# <div class="col-start-1 row-start-3 space-y-3 px-4">
        <button type="button" class="bg-violet-100 text-violet-700 border-2 border-white text-base font-semibold px-6 py-2 rounded-lg">Check availability</button>
      </div> %>
      <div class="w-full h-96 grid grid-cols-3 grid-rows-2 gap-2">
        <div class="relative col-span-3 row-span-2 md:col-span-2">
          <img src="https://images.unsplash.com/photo-1524758631624-e2822e304c36?ixlib=rb-1.2.1&ixid=MnwxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80" alt="" class="absolute inset-0 w-full h-full object-cover bg-gray-100 sm:rounded-md" />
        </div>
        <div class="relative hidden md:block">
          <img src="https://images.unsplash.com/photo-1517502884422-41eaead166d4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1325&q=80" alt="" class="absolute inset-0 w-full h-full object-cover rounded-md bg-gray-100" />
        </div>
        <div class="relative hidden md:block">
          <img src="https://images.unsplash.com/photo-1525896544042-354764aa27e6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80" alt="" class="absolute inset-0 w-full h-full object-cover rounded-md bg-gray-100" />
        </div>
      </div>


    <div class="p-10">
      <% @spaces.each do |space| %>
        <%= render 'space', space: space %>
      <% end %>
         <div class="flex justify-end">
      <%= link_to 'Add Space', new_venue_space_path(@venue), class:'py-2 px-4 no-underline bg-blue-200 text-blue-900 rounded-md' %>
      <div>
        <svg xmlns=“http://www.w3.org/2000/svg” class="icon icon-tabler icon-tabler-plus" width=“44” height="44" viewBox=“0 0 24 24” stroke-width="1.5" stroke=“#2C3E50” fill=“none” stroke-linecap=“round” stroke-linejoin=“round”>
          <path stroke=“none” d=“M0 0h24v24H0z” fill=“none”/>
          <line x1="12" y1="5" x2="12" y2=“19” />
          <line x1="5" y1="12" x2="19" y2=“12” />
        </svg>
      </div>
    </div>
    </div>


  </div>
</section>

<%# SPACES %>
<section class="bg-white text-gray-600 body-font">
  <div class="container px-5 pb-24 mx-auto flex">
  <%# SPACE CARDS %>
    <div class="w-2/3">
      <div class="-m-4">
        <div class="p-4">
          <div class="h-full border-2 border-gray-200 border-opacity-60 rounded-xl shadow overflow-hidden">
            <img class="lg:h-48 md:h-36 w-full object-cover object-center" src="https://images.unsplash.com/photo-1431540015161-0bf868a2d407?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80" alt="blog">
            <div class="p-6">
              <h1 class="title-font text-lg font-medium text-gray-900 mb-3">Space Name</h1>
              <h2 class="tracking-widest text-xs title-font font-medium text-gray-400 mb-1"><%= @venue.name %></h2>
              <p class="leading-relaxed mb-3">Photo booth fam kinfolk cold-pressed sriracha leggings jianbing microdosing tousled waistcoat.</p>
              <div class="flex-row justify-between">
                <div class="flex">
                  <button class="flex-col text-white py-2 px-12 focus:outline-none hover:bg-blue-600 rounded-md text-lg bg-gradient-to-t from-blue-900 via-blue-600 to-blue-500">Book now</button>
                </div>
                <div class="flex-row text-gray-400 mr-3 inline-flex items-right lg:ml-auto md:ml-0 ml-auto leading-none text-sm pl-3 py-1 border-l-2 border-gray-200">
                  <i class="fas fa-laptop pr-2"></i>
                  <p>12 seats </p>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>


    <div class="p-10">
      <% @spaces.each do |space| %>
        <%= render 'space', space: space %>
      <% end %>
         <div class="flex justify-end">
      <%= link_to 'Add Space', new_venue_space_path(@venue), class:'py-2 px-4 no-underline bg-blue-200 text-blue-900 rounded-md' %>
    </div>

    </div>

    <%# BOOK BUTTONS %>
    <%# <div class="w-1/3 h-96 bg-white shadow rounded">
      <div class="flex flex-col w-64 p-8 -m-4">
        <div class="py-2">
          <button class="text-white py-2 px-12 focus:outline-none hover:bg-blue-600 rounded-md text-lg bg-gradient-to-t from-blue-900 via-blue-600 to-blue-500">Book now
          </button>
        </div>

        <div class="py-2">
          <button class="text-white py-2 px-12 focus:outline-none hover:bg-blue-600 rounded-md text-lg bg-gradient-to-t from-blue-900 via-blue-600 to-blue-500">Book now
          </button>
        </div>

        <div class="py-2">
          <button class="text-white py-2 px-12 focus:outline-none hover:bg-blue-600 rounded-md text-lg bg-gradient-to-t from-blue-900 via-blue-600 to-blue-500">Book now
          </button>
        </div>
      </div>
    </div> %>
  </div>
</section>

<%# MAP %>
<section>

</section>

<%#
          <% @spaces.each do |space| %>
            <%# <%= render 'space', space: space
          <% end %>

app/views/spaces/new.html.erb
<div class="p-2 max-w-xl mx-auto">
<section class="footer-ht bg-white p-8">
  <div class="d-flex justify-content-center">
    <div class="h-full mb-4 p-2 rounded-2xl">
      <h1 class="text-xl d-flex justify-content-center mt-4 mb-3 font-weight-bold"> Add the space </h1>
      <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
        <div class="flex flex-col">
          <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
              <div class="p-3 max-w-xxl mx-auto">
                <%= render 'form' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
</div>

app/views/spaces/show.html.erb
<h1>Booked</h1>


<% @space.bookings.each do |booking| %>
    <%= booking.user.email %>
    <%= booking.start.strftime("%d/%m/%Y %I-%M%p") %>
    <%= booking.finish.strftime("%d/%m/%Y %I-%M%p") %> <br>
<% end %>