config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get 'login', to: 'devise/sessions#new', as: :login
  end
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :spaces, except: [:new, :create, :index] do
    resources :bookings, only: [:new, :create ]
  end

  resources :venues do
    resources :spaces, only: [:new, :create, :index] do
      resources :bookings, only: [:show ]
    end
  end

  resources :bookings, only: [:index, :destroy]
  get 'dashboard', to: 'dashboards#show', as: :dashboard


  namespace :api, defaults: { format: :json } do
    post 'webpush/subscribe', to: 'webpush#subscribe'
  end

end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :space

  validates :start, presence: true
  validates :finish, presence: true
  
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[destroy]
  before_action :set_space, only: %i[new create]
  skip_before_action :verify_authenticity_token, only: [:create]

  def index
    @bookings = current_user.bookings
  end

  def show
    @booking = Booking.where(params[:space_id])
  end

  # new_venue_space_booking GET /spaces/:space_id/bookings/new(.:format)/bookings#new
  def new
    @booking = Booking.new
    #  http://localhost:3000/spaces/5/bookings/new?week_start=2021-11-29T00%3A00%3A00%2B10%3A30
    if params[:week_start] && params[:week_start] > DateTime.now

      @monday = DateTime.parse(params[:week_start])
    else
      @monday = DateTime.now.beginning_of_week

    end

    @bookings = Booking.where('start >= ? and finish <= ?', @monday - 1.days, @monday + 7.days)
  end

  #  venue_space_bookings POST  /spaces/:space_id/bookings(.:format)/bookings#create
  def create
    @booking = Booking.new(booking_params)
    @booking.space = @space
    @booking.user = current_user
    if params[:week_start] && params[:week_start] > DateTime.now
      @monday = DateTime.parse(params[:week_start])
    else
      @monday = DateTime.now.beginning_of_week
    end
    
    if @booking.save
      redirect_to bookings_path
    else
      render :new
    end
  end

  def destroy
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def set_space
    @space = Space.find(params[:space_id])
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:venue_id, :space_id, :start, :finish)
  end
end

app/views/bookings/index.html.erb
<section class="footer-ht bg-white p-8">
  <div class="d-flex justify-content-center">
    <div class="h-full mb-4 p-2 rounded-2xl">
      <h1 class="text-xl d-flex justify-content-center mt-4 mb-3 font-weight-bold"> All Bookings </h1>
      <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
        <div class="flex flex-col">
          <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
              <table class="min-w-full divide-y divide-gray-200">
                <thead class="bg-grey-100">
                  <tr>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Room
                    </th>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Start day
                    </th>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Finish day
                    </th>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    </th>
                  </tr>
                </thead>
                <tbody class="bg-white divide-y divide-gray-200">
                  <% @bookings.each do |booking| %>
                    <tr>
                      <td class="px-6 py-4 whitespace-nowrap">
                          <div class="text-sm font-medium text-gray-900">
                            <%= booking.space.name %>
                          </div>
                      </td>
                      <td class="px-6 py-4 whitespace-nowrap">
                        <div class="text-sm text-gray-900">
                          <%=  booking.start.strftime("%d/%m/%Y %I-%M%p")%>
                        </div>
                      </td>
                      <td class="px-6 py-4 whitespace-nowrap">
                        <div class="text-sm text-gray-900">
                          <%= booking.finish.strftime("%d/%m/%Y %I-%M%p")%>
                        </div>
                      </td>
                      <td class="px-6 py-4 whitespace-nowrap">
                        <div class="text-sm text-gray-900">
                          <%= link_to 'Delete', booking_path(booking), method: :delete, data: { confirm: "Are you sure you want to remove your booking?"} %>
                        </div>
                      </td>
                    </tr>
                  <% end  %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
      <br>
    <div class="d-flex justify-content-end">
    <%= link_to 'Back', venues_path , class:"flex-col text-white py-1 px-6 focus:outline-none hover:bg-blue-600 rounded-md text-lg bg-gradient-to-t from-blue-900 via-blue-600 to-blue-500"%>
  </div>
</section>

app/views/bookings/new.html.erb
<section class="footer-ht bg-white p-8">
  <div class="container">
    <div style="text-align: center"><h1>Choose your date and time</h1></div>
    <% start_time = 9 %>
    <div data-controller="booking" class="d-flex flex-column align-items-center">
      <table class="booking-grid">
        <div class="container" style="text-align: center" >
          <div class="space">
              Week:
              <%= link_to 'Prev', new_space_booking_path(@space, week_start: @monday - 7.day), data: {turbolinks:"false"} %>
              |
              <%= link_to 'Next', new_space_booking_path(@space, week_start: @monday + 7.day), data: {turbolinks:"false"} %>
          </div>
          <tr style="text-align:center">
            <td></td>
            <td>Mon</td>
            <td>Tue</td>
            <td>Wed</td>
            <td>Thu</td>
            <td>Fri</td>
          </tr>
          <tr>
            <td></td>
            <% 5.times do |index_day| %>
                <td style="text-align:center"><%= (@monday + index_day.days).strftime('%d/%m') %></td>
            <% end %>
          </tr>
          <% 8.times do |index_hr| %>
            <tr>
              <td class="relative w-16 text-xs text-gray-600 p-3" >
                  <h4 class="absolute top-0 transform -translate-y-1/2 "><%= @monday.change({hour: 9 + index_hr}).strftime("%l %p")%></h4>
              </td>
              <% 5.times do |index_day| %>
                <% start_slot = (@monday + index_day.days).change({ hour: start_time + index_hr}) %>
                <% end_slot = start_slot + 1.hour %>
                <% booking_count = @bookings.where('space_id = ? and start <= ? and finish >= ?', @space.id, start_slot, end_slot).count %>
                <% available = @space.capacity - booking_count %>
                <% start = (@monday + index_day.days).change({ hour: start_time + index_hr})%>
                <td>
                  <% remaing_capacity = (available.to_f / @space.capacity.to_f)*100 %>
                  <div class="<% if remaing_capacity == 0 %>
                  availability-red
                  <% elsif remaing_capacity < 50 && remaing_capacity > 0 %>
                  availability-dark-green
                    <% elsif remaing_capacity >= 50 && remaing_capacity < 70  %>
                  availability-green
                    <% elsif remaing_capacity >= 70 && remaing_capacity < 100  %>
                  availability-light-green
                  <% else %>
                  availability-white
                  <% end%>" id="1d" data-action="click->booking#selectDateTime" data-datetime="<%= start%>">
                      <% booking_count %>
                      <p><%= available %> left</p>
                  </div>
                </td>
              <% end %>
            </tr>
          <% end %>
          <tr>
            <td class="relative w-16 text-xs text-gray-600 p-3">
                <h4 class="absolute top-0 transform -translate-y-1/2 "><%= @monday.change({hour: 17}).strftime("%l %p") %></h4>
            </td>
          </tr>
            <td></td>
        </div>
      </table>
      <%= simple_form_for ([@space, @booking]) do |f| %>
        <%= f.input :start, as: :string, label: false, input_html: {class: 'd-none', data: {booking_target:'start'}} %>
        <%= f.input :finish, as: :string, label: false, input_html: {class: 'd-none', data: {booking_target:'finish'}} %>
        <%= f.submit class: 'flex-col text-white py-1 px-6 focus:outline-none hover:bg-blue-600 rounded-md text-lg bg-gradient-to-t from-blue-900 via-blue-600 to-blue-500' %>
      <% end %>
    </div>
  </div>
</section>

app/views/bookings/show.html.erb
<h1>Availability</h1>
<%= @booking = Booking.where(params[:space_id]) %>