config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get 'login', to: 'devise/sessions#new', as: :login
  end
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :spaces, except: [:new, :create, :index] do
    resources :bookings, only: [:new, :create ]
  end

  resources :venues do
    resources :spaces, only: [:new, :create, :index] do
      resources :bookings, only: [:show ]
    end
  end

  resources :bookings, only: [:index, :destroy]
  get 'dashboard', to: 'dashboards#show', as: :dashboard


  namespace :api, defaults: { format: :json } do
    post 'webpush/subscribe', to: 'webpush#subscribe'
  end

end

app/views/shared/_footer.html.erb
<footer class="max-h-5 text-gray-400 bg-gray-800 body-font mx-auto">
  <div class="container px-5 py-8 mx-auto flex items-center sm:flex-row flex-col">
    <a class="flex title-font font-medium items-center md:justify-start justify-center text-white">
      <svg xmlns="https://tailwindui.com/img/logos/workflow-mark-blue-600.svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-blue-500 rounded-full" viewBox="0 0 24 24">
        <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
      </svg>
      <span class="ml-3">Office Connect</span>
    </a>
    <p class="text-sm text-gray-400 sm:ml-4 sm:pl-4 sm:border-l-2 sm:border-gray-800 sm:py-2 sm:mt-0 mt-4">© 2021 Office Connect —
      <a href="https://www.instagram.com/p/CWuS4ErvlLO/?utm_source=ig_web_copy_link" class="text-gray-500 ml-1" target="_blank" rel="noopener noreferrer">@LeWagonBatch757</a>
    </p>
    <span class="inline-flex sm:ml-auto sm:mt-0 mt-4 justify-center sm:justify-start">
      <a class="text-gray-400">
        <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
          <path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z"></path>
        </svg>
      </a>
      <a class="ml-3 text-gray-400">
        <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
          <path d="M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z"></path>
        </svg>
      </a>
      <a class="ml-3 text-gray-400">
        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
          <rect width="20" height="20" x="2" y="2" rx="5" ry="5"></rect>
          <path d="M16 11.37A4 4 0 1112.63 8 4 4 0 0116 11.37zm1.5-4.87h.01"></path>
        </svg>
      </a>
      <a class="ml-3 text-gray-400">
        <svg fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="0" class="w-5 h-5" viewBox="0 0 24 24">
          <path stroke="none" d="M16 8a6 6 0 016 6v7h-4v-7a2 2 0 00-2-2 2 2 0 00-2 2v7h-4v-7a6 6 0 016-6zM2 9h4v12H2z"></path>
          <circle cx="4" cy="4" r="2" stroke="none"></circle>
        </svg>
      </a>
    </span>
</footer>

app/views/shared/_navbar.html.erb
<!-- requires Tailwind CSS v2.0+ -->
<div class="relative bg-gray-800">
  <div class="max-w-7xl mx-auto px-4 sm:px-6">
    <div class="flex justify-between items-center py-6 md:justify-start md:space-x-10">
      <div class="flex justify-start lg:w-0 lg:flex-1">
        <a href="#">
          <img class="h-8 w-auto sm:h-10" src="https://tailwindui.com/img/logos/workflow-mark-blue-600.svg" alt="">
        </a>
        <div class="navbar-brand ml-3 text-xl text-white"><%= link_to "Office Connect", root_path%>
        </div>
      </div>
      <div class="-mr-2 -my-2 md:hidden">
        <div class="relative" data-controller="dropdown">
          <button data-action="click->dropdown#toggle" data-dropdown-target="button" type="button" class="rounded-md p-2 inline-flex items-center justify-center text-gray-100 hover:text-gray-400 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-blue-600" aria-expanded="false">
            <!-- Heamburger menu -->
            <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
            </svg>
          </button>
          <div data-dropdown-target="menu" class="absolute pin-r mt-2 transform shadow transition hover:border-gray-600 hidden right-0">
            <div class="block w-80 justify-center bg-gray-800 py-1 px-8 leading-8 divide-y divide-gray-600 rounded-md border-gray-600 overflow-hidden">
              <%= link_to "About", about_path, class:"px-1 py-2 justify-center text-white text-decoration-none group flex items-center text-base font-medium hover:text-gray-600 hover:bg-gray-600" %>
              <%= link_to "Venues", venues_path, class:"px-1 py-2 justify-center text-white text-decoration-none group flex items-center text-base font-medium hover:text-gray-600 hover:bg-gray-600" %>
              <%= link_to "Booking", bookings_path, class:"px-1 py-2 justify-center text-white text-decoration-none group flex items-center text-base font-medium hover:text-gray-600 hover:bg-gray-600" %>
            </div>
          </div>
        </div>
      </div>
      <nav class="hidden md:flex space-x-10">
        <%= link_to "About", about_path, class:"text-gray-100 text-decoration-none group rounded-md inline-flex items-center text-base font-medium hover:text-gray-400 " %>
        <%= link_to "Venues", venues_path, class:"text-gray-100 text-decoration-none group rounded-md inline-flex items-center text-base font-medium hover:text-gray-400 " %>
        <%= link_to "Bookings", bookings_path, class:"text-gray-100 text-decoration-none group rounded-md inline-flex items-center text-base font-medium hover:text-gray-400" %>
      </nav>
      <div class="hidden md:flex items-center justify-end md:flex-1 lg:w-0">
        <% if current_user %>
            <%= button_to destroy_user_session_path, method: :delete, class:'whitespace-nowrap text-base font-medium text-gray-100 hover:text-gray-400' do %>
              Logout
            <% end %>
        <% else %>
            <%= link_to new_user_session_path, class:'whitespace-nowrap text-base font-medium text-gray-100 hover:text-gray-400' do %>
              Log in
            <% end %>
            <%= link_to new_user_registration_path, class:'ml-8 whitespace-nowrap inline-flex items-center justify-center px-4 py-2 shadow rounded-md shadow-sm text-base font-medium text-white bg-blue-600 hover:bg-blue-700' do %>
              Sign up
            <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>