config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get 'login', to: 'devise/sessions#new', as: :login
  end
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :spaces, except: [:new, :create, :index] do
    resources :bookings, only: [:new, :create ]
  end

  resources :venues do
    resources :spaces, only: [:new, :create, :index] do
      resources :bookings, only: [:show ]
    end
  end

  resources :bookings, only: [:index, :destroy]
  get 'dashboard', to: 'dashboards#show', as: :dashboard


  namespace :api, defaults: { format: :json } do
    post 'webpush/subscribe', to: 'webpush#subscribe'
  end

end

app/models/venue.rb
class Venue < ApplicationRecord
  belongs_to :user
  has_many :spaces, dependent: :destroy
  has_many :bookings, through: :spaces

  geocoded_by :address do |obj, results|
    if geo = results.first
      obj.latitude = geo.latitude
      obj.longitude = geo.longitude
      obj.street = geo.street
      obj.suburb = geo.suburb
      obj.state = geo.state
      obj.country = geo.country
    end
  end

  after_validation :geocode
  has_many_attached :photos
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_action :set_venue, only: %i[show edit update destroy]
  def index
    @venues = Venue.all
    # ::WebpushNotification.publish_user_action(
      #   user: current_user,
      #   title: "test",
      #   action: "Added"
      # )
    end

    def show
      @spaces = @venue.spaces
      # @markers = @venues.geocoded.map do |venue|
      #   {
      #     lat: venue.latitude,
      #     lng: venue.longitude
      #   }
      # end
  end

  def new
    @venue = Venue.new
    # authorize if owner -> yes. else no
  end

  def create
    @venue = Venue.new(venue_params)
    @venue.user = current_user
    if @venue.save
      redirect_to new_venue_space_path(@venue)
    else
      render :new
    end
  end

  def edit
    # authorize if owner -> yes. else no
  end

  def update
    if @venue.update(venue_params)
      redirect_to @venue, notice: 'Venue was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    # authorize if owner -> yes. else no
    @venue.destroy
    redirect_to venues_path
  end

  private

  def set_venue
    @venue = Venue.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def venue_params
    params.require(:venue).permit(:name, :address, photos: [])
  end
  # Use callbacks to share
end

app/views/venues/_form.html.erb
<%= simple_form_for @venue do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <%= f.input :name %>
    <%= f.input :address %>

    <%= f.input :photos, class:"btn btn-primary bg-blue", as: :file, input_html: { multiple: true } %>

    <%= f.button :submit, class:"d-flex justify-content-center text-white py-1 px-6 focus:outline-none hover:bg-blue-600 rounded-md text-lg bg-gradient-to-t from-blue-900 via-blue-600 to-blue-500" %>

<% end %>

app/views/venues/_info_window.html.erb
<h4><%= venue.name %></h4>
<p><%= venue.address %></p>

app/views/venues/_venue.html.erb
 <div class="w-full flex mb-3 p-1 rounded-md hover:bg-gray-200 shadow">
  <div class="overflow-hidden rounded-md flex-shrink-0 h-36 w-36 border-2 border-white inner-shadow">
    <%= cl_image_tag(venue.photos.first.key, width: 300, height: 300, crop: :fill) if venue.photos.attached? %>
  </div>
  <div class="p-2 pl-4 flex flex-col justify-between flex-grow-1">
<%# Put address at the bottom of the name DIV %>
    <div class="flex-col justify-between">
      <div class="flex-row">
        <%= link_to venue_path(venue), class:'group hover:text-gray-500' do %>
          <h2 class="text-xl font-bold font-sans group-hover:text-gray-800"><%= venue.name %></h2>
        <% end %>
      </div>
      <div class="flex-row">
        <%= link_to venue_path(venue), class:'group hover:text-gray-400' do %>
          <h4 class="text-sm font-light text-gray-600"><%= venue.address %></h4>
        <% end %>
      </div>
    </div>

    <%# BUTTONS %>
    <div class="flex justify-end items-center">

        <%= link_to venue_path(venue), class:'p-1 group text-color-rgb(44 82 130) hover:no-underline' do %>
          <div class="d-flex p-1 rounded-md border-2 border-gray-400 items-center group-hover:bg-gray-800 group-hover:text-white">
            <div class="flex px-3 text-gray-700 group-hover:text-white">
              <i class="fas fa-plus-square fa-lg pt-1"></i>
              <p class="px-2">See more</p>
            </div>
          </div>
        <% end %>

      <% if current_user.venues.include?(venue) %>
        <%= link_to edit_venue_path(venue), class:'p-2 group text-color-rgb(44 82 130) hover:no-underline' do %>
          <div class="d-flex p-1 rounded-md border-2 border-gray-400 items-center group-hover:bg-gray-800 group-hover:text-white">
            <div class="flex px-3 text-gray-700 group-hover:text-white">
              <i class="fas fa-user-edit fa-lg pt-1"></i>
              <p class="px-2">Edit</p>
            </div>
          </div>
        <% end %>
      <% end %>

      <% if current_user.venues.include?(venue) %>
        <%= link_to  venue_path(venue), method: :delete, data: { confirm: "Are you sure you want to delete Venue?"}, class:'p-2 group text-color-rgb(44 82 130) hover:no-underline' do %>
          <div class="d-flex p-1 rounded-md border-2 border-gray-400 items-center group-hover:bg-gray-800 group-hover:text-white">
            <div class="flex px-3 text-gray-700 group-hover:text-white">
              <i class="fas fa-trash-alt fa-lg pt-1" style=""></i>
              <p class="px-2">Delete</p>
            </div>
          </div>
        <% end %>
      <% end %>

<%# class:'text-white py-1 px-6 focus:outline-none hover:bg-blue-600 rounded-md text-lg bg-gradient-to-t from-blue-900 via-blue-600 to-blue-500' %>
    </div>
  </div>
 </div>

app/views/venues/edit.html.erb
<section class="footer-ht bg-white p-8">
  <div class="d-flex justify-content-center">
    <div class="h-full mb-4 p-2 rounded-2xl">
      <h1 class="text-xl d-flex justify-content-center mt-4 mb-3 font-weight-bold"> Edit the venue </h1>
      <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
        <div class="flex flex-col">
          <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
              <div class="p-3 max-w-xxl mx-auto">
                <%= render 'form', venue: @venue %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/venues/index.html.erb
<div class="container bg-white w-screen top-0" style=" <%# height: calc(100vh - 70px) %>">
  <div class="h-full p-10">
    <% @venues.each do |venue| %>
      <%= render 'venue', venue: venue %>
    <% end %>
    <div class="flex justify-end">
      <%= link_to 'Add Venue', new_venue_path(@venue), class:'flex-col text-white py-1 px-6 focus:outline-none hover:bg-blue-600 rounded-md text-lg bg-gradient-to-t from-blue-900 via-blue-600 to-blue-500' %>
    </div>
  </div>
</div>

app/views/venues/new.html.erb
<div class="p-2 max-w-xl mx-auto">
<section class="footer-ht bg-white p-8">
  <div class="d-flex justify-content-center">
    <div class="h-full mb-4 p-2 rounded-2xl">
      <h1 class="text-xl d-flex justify-content-center mt-4 mb-3 font-weight-bold"> Add the venue </h1>
      <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
        <div class="flex flex-col">
          <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
              <div class="p-3 max-w-xxl mx-auto">
                <%= render 'form', venue: @venue %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
</div>

app/views/venues/show.html.erb
<section class="bg-white">
  <div class="container mx-auto">
    <div class="sm:px-8 sm:py-6 md:py-10">
      <div class="relative z-10 pb-3 sm:bg-none">
        <h2 class="text-xl font-semibold font-sans text-gray-900 sm:text-2xl sm:leading-7 sm:text-black md:text-3xl"><%= @venue.name %></h2>
        <div class="col-start-1 row-start-2 font-sans">
          <div class="flex items-left justify-between text-sm font-medium sm:mt-2 sm:mb-2">
            <div class="flex">
              <svg width="20" height="20" fill="currentColor" class="text-blue-700">
                <path d="M9.05 3.691c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.372 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.539 1.118l-2.8-2.034a1 1 0 00-1.176 0l-2.8 2.034c-.783.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.363-1.118l-2.8-2.034c-.784-.57-.381-1.81.587-1.81H7.03a1 1 0 00.95-.69L9.05 3.69z"></path>
              </svg>
              <div class="ml-1">
                <span class="text-gray-900">4.94</span>
                <span class="sm:hidden md:inline">(28)</span>
              </div>
              <div class="text-base font-normal mx-2">·</div>
              <p class="text-sm font-medium text-gray-700 sm:mb-1"><%= @venue.address %></p>
            </div>
            <div class="flex justify-end">
              <%= link_to '+ New space', new_venue_space_path(@venue), class:'py-1 px-2 no-underline border text-blue-900 rounded-md' %>
            </div>
          </div>


      <div class="w-full h-96 grid grid-cols-3 grid-rows-2 gap-2">
        <div class="relative col-span-3 row-span-2 md:col-span-2">
          <div class="absolute inset-0 w-full h-full object-cover bg-gray-100 sm:rounded-md">
          </div>
          <% if @venue.photos.first.present? %>
            <img src="<%= cl_image_path @venue.photos.first.key %>" alt="" class="absolute inset-0 w-full h-full object-cover bg-gray-100 sm:rounded-md">
          <% end %>
        </div>

        <div class="relative hidden md:block">
        <% if @venue.photos.second.present? %>
          <img src="<%= cl_image_path @venue.photos.second.key %>" alt="" class="absolute inset-0 w-full h-full object-cover rounded-md bg-gray-100">
        <% end %>
        </div>
        <div class="relative hidden md:block">
        <% if @venue.photos.third.present? %>
          <img src="<%= cl_image_path @venue.photos.third.key %>" alt="" class="absolute inset-0 w-full h-full object-cover rounded-md bg-gray-100">
        <% end %>
        </div>
      </div>


  </div>
</section>

<%# CHECK AVAILABILITY %>
  <%# <div class="col-start-1 row-start-3 space-y-3 px-4">
    <button type="button" class="bg-violet-100 text-violet-700 border-2 border-white text-base font-semibold px-6 py-2 rounded-lg">Check availability</button>
  </div> %>


<%# SPACES %>
<section class="bg-white text-gray-600 body-font">
  <div class="container px-5 pb-24 mx-auto flex">
  <%# SPACE CARDS %>
    <div class="w-1/2">
      <div class="-m-6">
        <% @venue.spaces.each do |space| %>
          <%= render 'spaces/space', space: space %>
        <% end %>
      </div>
    </div>

  <%# MAP %>
  <%# <div class="block px-5 pb-24 mx-auto flex"> %>
    <div class="w-1/2">
      <div class="relative pl-2 sticky top-4">
        <%# <%= render 'venues/venue', venue: venue %>
        <div id="map"
        class="rounded-xl"
          style="width: 100%; height: 600px;"
          data-markers="<%= [{lat: @venue.latitude, lng: @venue.longitude}].to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
        </div>
      </div>
    <%# </div> %>
  </div>
</section>